### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by lebron12332** [lifuguan/pixelsplat#1]
I run ```python3 -m src.main +experiment=re10k```, but raises a problem as follows:

AttributeError: Can't pickle local object 'get_data_shim.<locals>.combined_shim'. Did you mean: '_return_value'?

I do not know how to solve it? Can you give me some advice?

**Comment by lifuguan** [comment]
Sorry for the misunderstanding, this repo is not official code for PixelSplat, please follow th official repo https://github.com/dcharatan/pixelsplat to reproduce the result.
